In [1]:
import numpy as np

In [11]:
def signum(x):
    return np.where(x>=0,1,-1)

In [12]:
def train_bam(X,Y):
    return np.dot(X.T,Y)

In [13]:
def recall(W,pattern,steps=50):
    for _ in range(steps):
        pattern=signum(np.dot(pattern,W))
    return pattern

In [14]:
X=np.array([[1,1,-1],[1,-1,1],[-1,1,1]])
Y=np.array([[-1,-1,1],[-1,1,-1],[1,-1,-1]])

In [15]:
W=train_bam(X,Y)
W

array([[-3,  1,  1],
       [ 1, -3,  1],
       [ 1,  1, -3]])

In [16]:
for i,x in enumerate(Y):
    recall_x=recall(W,x)
    print(recall_x)

[-1 -1  1]
[-1  1 -1]
[ 1 -1 -1]


In [ ]:
# import numpy as np

# def signum(x):
#     """
#     The signum activation function, which returns 1 if x is non-negative, else -1.

#     Args:
#     x (array): The input array on which to apply the signum function.

#     Returns:
#     array: An array where each element is 1 if the corresponding input element is >= 0, else -1.
#     """
#     return np.where(x >= 0, 1, -1)

# def train_bam(X, Y):
#     """
#     Train a Bidirectional Associative Memory (BAM) model.

#     Args:
#     X (array): An array of input patterns.
#     Y (array): An array of output patterns.

#     Returns:
#     array: The weight matrix W obtained from the outer product of X and Y.
#     """
#     return np.dot(X.T, Y)

# def recall(W, pattern, steps=50):
#     """
#     Recall phase of the BAM, where a pattern is iteratively updated using the weight matrix.

#     Args:
#     W (array): The weight matrix of the BAM.
#     pattern (array): The initial pattern to recall the associated pattern.
#     steps (int): The number of iterations to update the pattern.

#     Returns:
#     array: The recalled pattern after 'steps' iterations.
#     """
#     for _ in range(steps):
#         pattern = signum(np.dot(pattern, W))
#     return pattern

# # Define the input patterns and their associated output patterns.
# X = np.array([[1, 1, -1], [1, -1, 1], [-1, 1, 1]])
# Y = np.array([[-1, -1, 1], [-1, 1, -1], [1, -1, -1]])

# # Train the BAM and obtain the weight matrix W.
# W = train_bam(X, Y)

# # Recall the patterns using the trained weight matrix.
# for i, x in enumerate(Y):
#     recall_x = recall(W, x)
#     print(f"Recalled pattern for input {x}: {recall_x}")
